[package]
name = "rayon"
version = "0.1.0"
authors = ["christoffer"]

[dependencies]
image = "0.6.1"
lazy_static = "0.2.1"
nalgebra = "0.10.1"
noise = "0.2.0"
num = "0.1.30"
rand = "0.3.13"
typenum = "1.3.2"
